name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thankyou for creating your first issue for this repo! Hopefully someone, somewhere will get to it eventually. If not: google it some more and cross your fingers.'
        pr-message: 'Thankyou for creating your first PR! Contributions like yours is what it is all about. Keep it up!'

